# Generated by Django 4.2.4 on 2023-10-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ONG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('nome_comercial', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18)),
                ('celular', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=255)),
                ('senha2', models.CharField(default='seu_valor_padrao_aqui', max_length=255)),
            ],
        ),
    ]
