# Generated by Django 4.2.4 on 2023-10-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_alter_ong_email_alter_ong_senha2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
