# Generated by Django 4.2.4 on 2023-10-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_alter_ong_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('forma_pagamento', models.CharField(choices=[('pix', 'PIX'), ('boleto', 'Boleto')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ong_parceiras', models.CharField(choices=[('Empresa 1', 'Empresa 1'), ('Empresa 2', 'Empresa 2'), ('Empresa 3', 'Empresa 3')], max_length=100)),
            ],
        ),
    ]
