# Generated by Django 4.2.5 on 2023-10-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0004_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='forma_pagamento',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='forma_Pagamento',
            field=models.CharField(choices=[('pix', 'PIX'), ('boleto', 'Boleto')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
